# Overlay shape for a real, generated Chatterino7 patch.
# Do not use this until patches/chatterino7-expose-c2-windows.patch exists and
# was generated by git diff against the exact SevenTV/chatterino7 source used by
# your nixpkgs chatterino7 package.

(final: prev: {
  chatterino7 = prev.chatterino7.overrideAttrs (old: {
    patches = (old.patches or []) ++ [
      (chatterinoPlugins + "/patches/chatterino7-expose-c2-windows.patch")
    ];
  });
})
